<a href="https://colab.research.google.com/github/Nunticha24/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

#Numpy Array

##สร้าง numpy array (matrix) จาก list

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

###matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

##สร้าง matrix เริ่มต้น (zeros, ones)

In [7]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np_200 = 200 * np.ones((4,7)) #อยากได้ค่า matrix 200 ถ้าอยากได้ค่าไหนให้เอาค่านั้นมาคูณ
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##สร้าง matrix random

In [12]:
np.random.rand(5,5) #random เลขมาจาก normal distribution ที่มี mu = 0 std = 1

array([[0.88080251, 0.17657295, 0.14774708, 0.19740446, 0.49457987],
       [0.73548941, 0.00757501, 0.5652943 , 0.64773102, 0.64776675],
       [0.35602713, 0.43466155, 0.64667415, 0.57940385, 0.7180628 ],
       [0.80389953, 0.98965761, 0.46380042, 0.37916825, 0.7442683 ],
       [0.08609306, 0.11093703, 0.70092619, 0.44506452, 0.1062898 ]])

In [13]:
2+(5*np.random.rand(3,3)) #random เลขมาจาก normal distribution ที่มี mu = 2 std = 5

array([[4.39692453, 6.84979176, 5.71176417],
       [3.91246519, 3.94549493, 4.19202915],
       [3.28109636, 3.03160916, 5.84578594]])

In [14]:
np.random.randint(5,11,(4,5)) #random เลขจำนวนเต็มระหว่าง (5,11) ขนาด (4x5)

array([[ 6, 10, 10,  9,  7],
       [10,  9, 10,  7,  8],
       [10,  5,  5,  5,  5],
       [ 6, 10,  7, 10,  5]])